# Generated by Django 2.2.7 on 2019-11-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasolyne_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_link',
            field=models.CharField(default='n/a', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='video_thumbnail',
            field=models.CharField(default='n/a', max_length=100),
        ),
    ]
