# Generated by Django 2.2.7 on 2019-11-28 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gasolyne_app', '0002_auto_20191128_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video_thumbnail',
        ),
    ]
